app/routes/auth_routes.py
from flask import Blueprint, request, session, redirect, url_for
from app.models import User

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['POST'])
def login():
    username = request.form['username']
    password = request.form['password']

    user = User.query.filter_by(name=username).first_or_404()

    if user and user.check_password(password):
        session['user_id'] = user.id
        session['username'] = user.name
        return redirect(url_for('user.index'))
    else:
        return redirect(url_for('user.index'))


@auth_bp.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect(url_for('user.index'))

app/routes/game_routes.py
from flask import (
    Blueprint, request, session,
    redirect, url_for, render_template, flash
)
from app.models import Game, Comment, db

game_bp = Blueprint('game', __name__)


@game_bp.route('/create_game', methods=['GET', 'POST'])
def create_game():
    if request.method == 'POST':
        form_name = request.form.get('name')

        form_categories = request.form.getlist('category')

        flash('Jogo criado com sucesso!', 'success')

        new_game = Game(name=form_name)
        new_game.set_categories(form_categories)
        db.session.add(new_game)
        db.session.commit()
        return redirect(url_for('user.index'))     
    return render_template('register_game.html')


@game_bp.route('/create_comment/<int:game_id>', methods=['POST'])
def create_comment(game_id):

    text = request.form['text']
    rating = int(request.form['rating'])

    if 'user_id' in session:
        new_comment = Comment(user_id=session['user_id'],
                              game_id=game_id,
                              text=text,
                              rating=rating)

    db.session.add(new_comment)
    db.session.commit()

    flash('Comment created successfully!', 'success')

    return redirect(url_for('game.game_by_id', id=game_id))


@game_bp.route("/game/<int:id>", methods=['GET'])
def game_by_id(id):
    game = db.get_or_404(Game, id)

    # Query to get all comments associated with the game_id
    comments = Comment.query.filter_by(game_id=game.id).all()

    return render_template('view_game.html', game=game, comments=comments)

app/routes/user_routes.py
from flask import (
    Blueprint, request, session, jsonify,
    redirect, url_for, render_template, flash
)
from app.models import User, Game, StressRecord, db
from app.utils import login_required, calculate_weight
from datetime import datetime, timezone
from DadosEstaticos import default_user_prefs

user_bp = Blueprint('user', __name__)


@user_bp.route('/')
def index():
    games = Game.query.all()

    if 'user_id' in session:
        user = db.get_or_404(User, session['user_id'])
        games_with_weights = [
            (game, calculate_weight(game, user))
            for game in games
            ]
        games_with_weights.sort(key=lambda x: x[1], reverse=True)

        latest_stress_record = user.get_latest_stress_record()
        stress_level = latest_stress_record.stress_level if latest_stress_record else 0

        return render_template('index.html',
                               games_with_weights=games_with_weights,
                               user=user,
                               stress_level=stress_level)

    else:
        games_with_weights = [(game, 0) for game in games]
        return render_template('index.html',
                               games_with_weights=games_with_weights)


@user_bp.route('/users', methods=['POST'])
def create_user():
    data = request.get_json()
    new_user = User(name=data['name'])
    db.session.add(new_user)
    db.session.commit()
    return jsonify({'message': 'User created'}), 201


@user_bp.route("/users/<int:id>", methods=['GET'])
@login_required
def user_by_id(id):
    user = db.get_or_404(User, id)
    return render_template('view_user.html', user=user)


@user_bp.route("/profile", methods=['GET'])
def view_user_profile():
    if 'user_id' in session:

        user = db.get_or_404(User, session['user_id'])
        stress_data = (StressRecord.query
                       .filter_by(user_id=user.id)
                       .order_by(StressRecord.date)
                       .all())
        labels = [record.date.strftime('%Y-%m-%d') for record in stress_data]
        data = [record.stress_level for record in stress_data]
        latest_stress_record = user.get_latest_stress_record()
        stress_level = latest_stress_record.stress_level if latest_stress_record else 0
        return render_template('view_user.html',
                               user=user,
                               data=data,
                               labels=labels,
                               stress_level=stress_level)
    return redirect(url_for('user.index'))


@user_bp.route('/users', methods=['GET'])
def get_users():
    users = User.query.all()
    return render_template('user_list.html', users=users)


@user_bp.route('/users/<int:id>', methods=['PUT'])
def update_user(id):
    user = db.get_or_404(User, id)
    data = request.get_json()
    if 'name' in data:
        user.name = data['name']
    db.session.commit()
    return jsonify({'message': 'User updated'}), 200


@user_bp.route('/users/<int:id>', methods=['POST'])
def delete_user(id):
    user = db.get_or_404(User, id)
    db.session.delete(user)
    db.session.commit()
    users = User.query.all()
    return render_template('user_list.html', users=users)


@login_required
@user_bp.route('/stress_record', methods=['GET', 'POST'])
def create_stress_record():
    if request.method == 'POST':
        q1 = int(request.form.get('question1'))
        q2 = int(request.form.get('question2'))
        q3 = int(request.form.get('question3'))
        q4 = int(request.form.get('question4'))
        q5 = int(request.form.get('question5'))
        q6 = int(request.form.get('question6'))
        q7 = int(request.form.get('question7'))
        q8 = int(request.form.get('question8'))
        q9 = int(request.form.get('question9'))
        q10 = int(request.form.get('question10'))

        # Os itens 4, 5, 7 e 8 são positivos e por esta razão devem ter a
        # pontuação revertida
        # Ex: 0 = 4, 1 = 3, 2 = 2, 3 = 1 e 4 = 0
        total_stress = (
            q1 + q2 + q3 + (4 - q4) +
            (4 - q5) + q6 + (4 - q7) +
            (4 - q8) + q9 + q10
        )

        print(f"Stress total {total_stress}", flush=True)

        if 'user_id' in session:
            usr_id = session['user_id']

        new_stress_record = StressRecord(user_id=usr_id,
                                         stress_level=total_stress,
                                         date=datetime.now(timezone.utc))
        db.session.add(new_stress_record)
        db.session.commit()

        return redirect(url_for('user.index'))
    return render_template('register_stress.html')


@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        genres = request.form.getlist('genres')
        play_time = request.form.getlist('play-time')
        game_style = request.form.getlist('game-style')
        interest_level = request.form.getlist('interest-level')

        new_user_prefs = default_user_prefs  # get the defaul user prefs dict

        if 'music' in genres:
            new_user_prefs["musical"] += 3
            new_user_prefs["sensorial"] += 2
            new_user_prefs["meditation"] += 1

        if 'story' in genres:
            new_user_prefs["narrative"] += 3
            new_user_prefs["adventure"] += 2
            new_user_prefs["rpg"] += 2

        if 'puzzle' in genres:
            new_user_prefs["puzzle"] += 3
            new_user_prefs["strategy"] += 2
            new_user_prefs["simulation"] += 1

        if 'art' in genres:
            new_user_prefs["painting"] += 3
            new_user_prefs["sensorial"] += 2
            new_user_prefs["meditation"] += 1

        if 'short-time' in play_time:
            new_user_prefs["arcade"] += 3
            new_user_prefs["casual"] += 2
            new_user_prefs["idle"] += 1

        if 'medium-time' in play_time:
            new_user_prefs["virtual-version"] += 3
            new_user_prefs["casual"] += 2

        if 'long-time' in play_time:
            new_user_prefs["simulation"] += 3
            new_user_prefs["strategy"] += 2
            new_user_prefs["rpg"] += 2
            new_user_prefs["adventure"] += 1

        if 'co-op' in game_style:
            new_user_prefs["co-op"] += 3
            new_user_prefs["social"] += 2

        if 'competitive' in game_style:
            new_user_prefs["competitive"] += 3
            new_user_prefs["strategy"] += 2

        if 'open-world' in game_style:
            new_user_prefs["open-world"] += 3
            new_user_prefs["adventure"] += 2

        if 'narrative' in game_style:
            new_user_prefs["narrative"] += 3
            new_user_prefs["adventure"] += 2
            new_user_prefs["rpg"] += 1

        if 'social' in game_style:
            new_user_prefs["social"] += 3
            new_user_prefs["co-op"] += 2

        if 'sports' in interest_level:
            new_user_prefs["sports"] += 3

        if 'somewhat' in interest_level:
            new_user_prefs["sports"] += 2

        if 'not-interested' in interest_level:
            new_user_prefs["sports"] -= 3

        if not (username and password and confirm_password):
            flash('Todos os campos são obrigatórios!', 'danger')
            return redirect(url_for('user.register'))

        if password != confirm_password:
            flash('As senhas não coincidem!', 'danger')
            return redirect(url_for('user.register'))

        # Check if a user with the same username already exists
        existing_user = User.query.filter_by(name=username).first()
        if existing_user:
            flash('Este nome de usuário já está em uso.', 'danger')
            return redirect(url_for('user.register'))

        new_user = User(name=username)
        new_user.set_password(password)
        new_user.set_prefs(new_user_prefs)
        db.session.add(new_user)
        db.session.commit()

        session['user_id'] = new_user.id
        session['username'] = new_user.name

        return redirect(url_for('user.index'))

    return render_template('register_user.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calmomila</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
</head>
<body>
    
    <!-- Barra de Navegação -->
    <header class="navbar navbar-expand-lg navbar-light bd-navbar sticky-top">
    <nav class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('user.index') }}">
            <img src="{{ url_for('static', filename='images/logo_3.svg') }}" alt="Camomila" style="height: 50px;">
            <span class="site-name">Calmomila</span>
          </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">

            {%if 'user_id' in session and session['username'] == 'admin'%}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Admin
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{{ url_for('user.get_users') }}">Usuarios</a>
                  <a class="dropdown-item" href="#">Jogos</a>
                </div>
            </li>
            {% endif %}

            {% if 'user_id' in session %}
            <li class="nav-item mr-3">
            <a class="nav-link" href="{{ url_for('user.get_users') }}">Usuarios</a>
            </li>
            {% endif %}

            {% if 'user_id' in session %}
            <li class="nav-item mr-3">
                <a class="nav-link" href="{{ url_for('game.create_game') }}">Cadastrar Jogo</a>
            </li>
            {% endif %}

            {% if 'user_id' not in session %}
            <li class="nav-item mr-3">
            <a class="nav-link" href="{{ url_for('user.register') }}">Sign up</a>
            </li>
            {% endif %}

            
            {% if 'user_id' in session %}
            <li class="nav-item mr-3">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
            {% endif %}

            {% if 'user_id' not in session %}
            <li class="nav-item mr-3">
                <button type="button" class="btn btn-outline-light" data-toggle="modal" data-target="#loginModal">Sign in</button>
            </li>
            {% endif %}
        </ul>
      </div>
    </nav>
  </header>
    
<main>
    {% block content %}{% endblock %}
</main>

<!-- Footer -->
<footer class="footer text-center text-lg-start bg-body-tertiary text-muted">
    <div class="text-center p-0" style="color: white;">
        © 2024 Copyright: Universidade de Brasília
      </div>
</footer>
  

    <!-- Modal Login -->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalLabel">Login</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ url_for('auth.login') }}" method="POST">
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" id="username" name="username" placeholder="Digite seu nome de usuario" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Senha</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Digite sua senha" required>
                        </div>
                        <!-- Center the button -->
                        <div class="d-flex justify-content-center mt-3">
                            <button type="submit" class="btn btn-primary">Sign in</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <!-- Scripts do Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}
{% block content %}

{% if 'user_id' in session %}
<!-- Profile Card Positioned in the Upper Right -->
<div class="col-md-12">
    <div class="profile-card mr-4 mt-3" style="position: absolute; top: 0px; right: 0px; width: 18rem;">
        <div class="card">
            <img src="https://cdn-icons-png.flaticon.com/512/3479/3479853.png" class="card-img-top" alt="Profile Picture">
            <div class="card-body">
                <h5 class="card-title">{{user.name}}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Level {{user.level}}</li>
                
                <li class="list-group-item">
                    <div class="d-flex justify-content-between">
                        <span>XP</span>
                        <span>{{ user.xp }}/100</span>
                    </div>
                    <div class="progress" style="height: 20px;">
                        <div class="progress-bar" role="progressbar" style="width: {{ user.xp }}%;" aria-valuenow="{{ user.xp }}" aria-valuemin="0" aria-valuemax="100">
                            {{ user.xp }} XP
                        </div>
                    </div>
                </li>

                <li class="list-group-item">
                    <div class="d-flex justify-content-between">
                        <span>Stress Level</span>
                        <span>{{ stress_level }}/40</span>
                    </div>
                    <div class="progress" style="height: 20px;">
                        <div class="progress-bar bg-danger" role="progressbar" style="width: {{ (stress_level / 40) * 100 }}%;" aria-valuenow="{{ stress_level }}" aria-valuemin="0" aria-valuemax="40">
                            {{ stress_level }} Stress
                        </div>
                    </div>
                </li>

            </ul>
            <div class="card-body">
                <a href="{{ url_for('user.view_user_profile') }}" class="card-link">Profile</a>
                <a href="{{ url_for('user.create_stress_record') }}" class="card-link">Registrar Estresse</a>
            </div>
        </div>
    </div>
</div>
{% endif %}

<div class="container", style="background-color: white">
    <div class="row">
        <!-- Games List -->
        <div class="col-md-12 mt-3">
            <h2>Recomendado para você</h2>
            <div class="row mt-3">
                {% for game, weight in games_with_weights %}
                <div class="col-md-3"> <!-- Add mb-4 class to add bottom margin -->
                    <a href="{{ url_for('game.game_by_id', id=game.id) }}" class="text-decoration-none text-dark">
                        <div class="card mx-auto" style="width: 16rem;">
                            <img src="{{ url_for('static', filename='images/game_icons/' + game.name.lower().replace(' ', '') + '.png') }}" alt="Game Logo" class="card-img-top">
                            <div class="card-body">
                                <h5 class="card-title">{{ game.name }}</h5>
                                <!-- Displaying average rating as stars -->
                                <div class="d-flex flex-row">
                                    {% set avg_rating = game.average_rating()|round(0, 'ceil')|int %}
                                    <!-- Render filled stars -->
                                    {% for i in range(1, avg_rating + 1) %}
                                        <i class="fas fa-star text-warning me-2"></i>
                                    {% endfor %}
                                    <!-- Render faded stars -->
                                    {% for i in range(avg_rating + 1, 6) %}
                                        <i class="far fa-star me-2" style="color: #aaa;"></i>
                                    {% endfor %}
                                </div>

                                <!-- Categories as colored buttons -->
                                <div class="mt-3">
                                    {% set category_colors = {
                                        "action": "#E57373",  
                                        "adventure": "#81C784",
                                        "arcade": "#7986CB",  
                                        "puzzle": "#cec14e",  
                                        "simulation": "#9575CD",  
                                        "strategy": "#4DD0E1",  
                                        "rpg": "#F48FB1",  
                                        "casual": "#FF8A65",  
                                        "virtual-version": "#A5D6A7",  
                                        "idle": "#64B5F6",  
                                        "musical": "#BA68C8",  
                                        "meditation": "#80CBC4",  
                                        "sensorial": "#FFAB91",  
                                        "painting": "#CE93D8",  
                                        "co-op": "#EF9A9A",  
                                        "competitive": "#90A4AE", 
                                        "narrative": "#FFCC80",  
                                        "social": "#A5D6A7",  
                                        "sports": "#FFB74D"  
                                    } %}
                                    
                                    {% for category in game.get_categories() %}
                                        <span class="badge badge-pill text-white" style="background-color: {{ category_colors.get(category, '#000') }};">
                                            {{ category }}
                                        </span>
                                    {% endfor %}
                                </div>
                                
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/register_game.html
{% extends "base.html" %}

{% block content %}

   <div class="content-container">
    <h2 class="text-center text-white">Cadastrar Jogo</h2>

    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            <div>
                {% for category, message in messages %}
                    <div class="flash {{ category }}">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}

    <form action="{{ url_for('game.create_game') }}" method="POST">

        <div class="form-group">
            <label for="name" class="text-white">Nome do Jogo</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Digite o nome do jogo" required>
        </div>

        
        <label class="text-white">Categorias</label>
        <div class="genre-options">
            <div class="genre-option">
                <input type="checkbox" id="action" name="category" value="action">
                <label for="action">Action</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="adventure" name="category" value="adventure">
                <label for="adventure">Adventure</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="arcade" name="category" value="arcade">
                <label for="arcade">Arcade</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="puzzle" name="category" value="puzzle">
                <label for="puzzle">Puzzle</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="simulation" name="category" value="simulation">
                <label for="simulation">Simulation</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="strategy" name="category" value="strategy">
                <label for="strategy">Strategy</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="rpg" name="category" value="rpg">
                <label for="rpg">RPG</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="casual" name="category" value="casual">
                <label for="casual">Casual</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="virtual-version" name="category" value="virtual-version">
                <label for="virtual-version">Virtual Version</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="idle" name="category" value="idle">
                <label for="idle">Idle</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="musical" name="category" value="musical">
                <label for="musical">Musical</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="meditation" name="category" value="meditation">
                <label for="meditation">Meditation</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="sensorial" name="category" value="sensorial">
                <label for="sensorial">Sensorial</label>
            </div>
            <div class="genre-option">
                <input type="checkbox" id="paiting" name="category" value="painting">
                <label for="paiting">Painting</label>
            </div>
        </div>
    
        
        <div class="text-center">
            <button type="submit" class="btn btn-outline-light">Cadastrar</button>
        </div>
    </form>

</div>
{% endblock %}

app/templates/user_list.html
{% extends "base.html" %}
{% block title %}Users{% endblock %}
{% block content %}

    <div class="container">

        {% for user in users %}
        <div class="row justify-content-md-center">

            <div class="col col-9">
                {{user.name}}
            </div>
            
            <div class="col-3">
                <form action="{{ url_for('user.delete_user', id=user.id) }}" method="POST" style="display:inline;">
                    <button type="submit" class="btn btn-danger">Apagar</button>
                </form>
            </div>
        </div>
        {% endfor %}

    </div>

{% endblock %}

app/templates/view_user.html
{% extends "base.html" %}
{% block title %}View User{% endblock %}
{% block content %}
    <div class="container" style="display: flex; justify-content: space-between; align-items: flex-start; padding: 20px; background-color: white">
        
        <!-- Gráfico de Estresse (lado esquerdo) -->
        <div style="flex: 1; margin-right: 20px;">
            <h1>Registros de Estresse</h1>
            <div style="height: 50vh; width: 100%;">
                <canvas id="myChart"></canvas>
            </div>
        </div>

        <!-- Card de Perfil do Usuário (lado direito) -->
        <div class="card" style="flex: 0 0 300px;">
            <img src="https://cdn-icons-png.flaticon.com/512/3479/3479853.png" class="card-img-top" alt="Profile Picture">
            <div class="card-body">
                <h5 class="card-title">{{ user.name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Level {{ user.level }}</li>
                
                <li class="list-group-item">
                    <div class="d-flex justify-content-between">
                        <span>XP</span>
                        <span>{{ user.xp }}/100</span>
                    </div>
                    <div class="progress" style="height: 20px;">
                        <div class="progress-bar" role="progressbar" style="width: {{ user.xp }}%;" aria-valuenow="{{ user.xp }}" aria-valuemin="0" aria-valuemax="100">
                            {{ user.xp }} XP
                        </div>
                    </div>
                </li>

                <li class="list-group-item">
                    <div class="d-flex justify-content-between">
                        <span>Stress Level</span>
                        <span>{{ stress_level }}/40</span>
                    </div>
                    <div class="progress" style="height: 20px;">
                        <div class="progress-bar bg-danger" role="progressbar" style="width: {{ (stress_level / 40) * 100 }}%;" aria-valuenow="{{ stress_level }}" aria-valuemin="0" aria-valuemax="40">
                            {{ stress_level }} Stress
                        </div>
                    </div>
                </li>
            </ul>
            <div class="card-body">
                <a href="{{ url_for('user.view_user_profile') }}" class="card-link">Profile</a>
                <a href="{{ url_for('user.create_stress_record') }}" class="card-link">Registrar Estresse</a>
            </div>
        </div>

    </div>

    <!-- Script para gerar o gráfico -->
    <script>
        const labels = {{ labels | tojson }};
 
        const data = {
            labels: labels,
            datasets: [{
                label: 'Estresse',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: {{ data | tojson }},
            }]
        };
 
        const config = {
            type: 'line',
            data: data,
            options: {
                maintainAspectRatio: false,
                scales: {
                    y: {
                        beginAtZero: true, // Começa o eixo y no zero
                        min: 0, // Define o valor mínimo do eixo y
                        max: 40, // Define o valor máximo do eixo y
                        ticks: {
                            stepSize: 5 // Define o intervalo entre as marcas do eixo y, ajustando conforme necessário
                        }
                    }
                }
            }
        };
 
        const myChart = new Chart(
            document.getElementById('myChart'),
            config
        );
    </script>
{% endblock %}